// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbsei0vCj1UhbMB4M47_oLArXWzcg052w',
    appId: '1:1013685733039:web:0e323938ff7d456d58765a',
    messagingSenderId: '1013685733039',
    projectId: 'social-media-4f53d',
    authDomain: 'social-media-4f53d.firebaseapp.com',
    storageBucket: 'social-media-4f53d.appspot.com',
    measurementId: 'G-FKXC3PV7MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ck7Ia_AOZEwuWPMMM8gf8SatBHPOevc',
    appId: '1:1013685733039:android:2bb0d9b854a23d1a58765a',
    messagingSenderId: '1013685733039',
    projectId: 'social-media-4f53d',
    storageBucket: 'social-media-4f53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIUYKU5KC6xv3ma6tXsVK_dIcFspl0lM',
    appId: '1:1013685733039:ios:f984f3d51d68fff358765a',
    messagingSenderId: '1013685733039',
    projectId: 'social-media-4f53d',
    storageBucket: 'social-media-4f53d.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIUYKU5KC6xv3ma6tXsVK_dIcFspl0lM',
    appId: '1:1013685733039:ios:f984f3d51d68fff358765a',
    messagingSenderId: '1013685733039',
    projectId: 'social-media-4f53d',
    storageBucket: 'social-media-4f53d.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbsei0vCj1UhbMB4M47_oLArXWzcg052w',
    appId: '1:1013685733039:web:86094101486d69a458765a',
    messagingSenderId: '1013685733039',
    projectId: 'social-media-4f53d',
    authDomain: 'social-media-4f53d.firebaseapp.com',
    storageBucket: 'social-media-4f53d.appspot.com',
    measurementId: 'G-DC5HV25EQZ',
  );
}
